"""Seed data for the 89 component types across 17 categories.

Called on startup to populate the component_types table.
Uses upsert to avoid duplicates on repeated restarts.
"""
from __future__ import annotations
from sqlalchemy.ext.asyncio import AsyncSession

from app.repositories.component_type_repo import ComponentTypeRepository


# ── Component Type Definitions ───────────────
# Each entry maps directly to ComponentType ORM fields.

COMPONENT_TYPES: list[dict] = [
    # ── Content Presentation ─────────────────
    {"type_id": "tabs", "display_name": "Tabbed Content", "category": "content-presentation", "icon": "layout", "scoring_enabled": False, "completion_capabilities": ["view", "interact", "audio"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["tab"]}, "tags": ["tabs", "content", "interactive"], "sort_order": 1, "schema": {"type": "object", "required": ["tabs"], "properties": {"tabs": {"type": "array", "minItems": 1, "items": {"type": "object", "required": ["id", "label", "content"], "properties": {"id": {"type": "string"}, "label": {"type": "string"}, "content": {"type": "string"}}}}}}},
    {"type_id": "accordion", "display_name": "Accordion", "category": "content-presentation", "icon": "list", "scoring_enabled": False, "completion_capabilities": ["view", "interact", "audio"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["panel"]}, "tags": ["accordion", "expandable", "content"], "sort_order": 2, "schema": {"type": "object", "required": ["panels"], "properties": {"panels": {"type": "array", "minItems": 1, "items": {"type": "object", "required": ["id", "title", "content"], "properties": {"id": {"type": "string"}, "title": {"type": "string"}, "content": {"type": "string"}}}}}}},
    {"type_id": "click-reveal", "display_name": "Click and Reveal", "category": "content-presentation", "icon": "eye", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["reveal-item"]}, "tags": ["click", "reveal", "interactive"], "sort_order": 3},
    {"type_id": "timeline", "display_name": "Timeline", "category": "content-presentation", "icon": "clock", "scoring_enabled": False, "completion_capabilities": ["view", "interact"], "default_completion_type": "view", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["event"]}, "tags": ["timeline", "chronological"], "sort_order": 4},
    {"type_id": "image-hotspots", "display_name": "Image Hotspots", "category": "content-presentation", "icon": "map-pin", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["hotspot"]}, "tags": ["image", "hotspots", "interactive"], "sort_order": 5},
    {"type_id": "layered-content", "display_name": "Layered Content", "category": "content-presentation", "icon": "layers", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["layer"]}, "tags": ["layers", "overlay", "content"], "sort_order": 6},
    {"type_id": "text-with-media", "display_name": "Text with Media", "category": "content-presentation", "icon": "file-text", "scoring_enabled": False, "completion_capabilities": ["view", "audio"], "default_completion_type": "view", "audio_support": {"perComponent": True, "perInteraction": False}, "tags": ["text", "media", "content"], "sort_order": 7},

    # ── Process & Flow ───────────────────────
    {"type_id": "step-by-step", "display_name": "Step-by-Step Process", "category": "process-flow", "icon": "list-ordered", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["step"]}, "tags": ["steps", "process", "sequential"], "sort_order": 10},
    {"type_id": "cycle-diagram", "display_name": "Cycle Diagram", "category": "process-flow", "icon": "refresh-cw", "scoring_enabled": False, "completion_capabilities": ["view", "interact"], "default_completion_type": "view", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["stage"]}, "tags": ["cycle", "diagram", "process"], "sort_order": 11},
    {"type_id": "flowchart", "display_name": "Flowchart", "category": "process-flow", "icon": "git-branch", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["flowchart", "diagram"], "sort_order": 12},
    {"type_id": "process-map", "display_name": "Process Map", "category": "process-flow", "icon": "map", "scoring_enabled": False, "completion_capabilities": ["view", "interact"], "default_completion_type": "view", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["node"]}, "tags": ["process", "map", "visual"], "sort_order": 13},
    {"type_id": "decision-tree", "display_name": "Decision Tree", "category": "process-flow", "icon": "git-merge", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["decision"]}, "tags": ["decision", "tree", "branching"], "sort_order": 14},

    # ── Interaction ──────────────────────────
    {"type_id": "drag-drop", "display_name": "Drag and Drop", "category": "interaction", "icon": "move", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["interact", "score"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["drag", "drop", "interactive"], "sort_order": 20},
    {"type_id": "flip-cards", "display_name": "Flip Cards", "category": "interaction", "icon": "rotate-cw", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["card"]}, "tags": ["flip", "cards", "reveal"], "sort_order": 21},
    {"type_id": "slider", "display_name": "Slider", "category": "interaction", "icon": "sliders", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["slider", "range", "interactive"], "sort_order": 22},
    {"type_id": "carousel", "display_name": "Carousel", "category": "interaction", "icon": "image", "scoring_enabled": False, "completion_capabilities": ["view", "interact"], "default_completion_type": "view", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["slide"]}, "tags": ["carousel", "slideshow", "gallery"], "sort_order": 23},
    {"type_id": "clickable-icons", "display_name": "Clickable Icons", "category": "interaction", "icon": "grid", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["icon"]}, "tags": ["icons", "clickable", "interactive"], "sort_order": 24},

    # ── Scenario-Based ───────────────────────
    {"type_id": "scenario", "display_name": "Scenario", "category": "scenario", "icon": "map", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["interact", "score"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["choice"]}, "tags": ["scenario", "real-world", "decision"], "sort_order": 30},
    {"type_id": "branching-scenario", "display_name": "Branching Scenario", "category": "scenario", "icon": "git-branch", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["interact", "score"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["branch"]}, "tags": ["branching", "scenario", "adaptive"], "sort_order": 31},
    {"type_id": "role-play", "display_name": "Role-Play Simulation", "category": "scenario", "icon": "users", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["dialogue"]}, "tags": ["role-play", "simulation", "dialogue"], "sort_order": 32},
    {"type_id": "case-study", "display_name": "Case Study", "category": "scenario", "icon": "book-open", "scoring_enabled": False, "completion_capabilities": ["view", "interact"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["case-study", "analysis"], "sort_order": 33},

    # ── Assessment ───────────────────────────
    {"type_id": "mcq", "display_name": "Multiple Choice", "category": "assessment", "icon": "check-circle", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["score"], "default_completion_type": "score", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["quiz", "mcq", "assessment"], "sort_order": 40, "schema": {"type": "object", "required": ["questions"], "properties": {"questions": {"type": "array", "minItems": 1, "items": {"type": "object", "required": ["id", "question", "options"], "properties": {"id": {"type": "string"}, "question": {"type": "string"}, "options": {"type": "array", "minItems": 2, "items": {"type": "object", "required": ["id", "text", "isCorrect"], "properties": {"id": {"type": "string"}, "text": {"type": "string"}, "isCorrect": {"type": "boolean"}}}}, "explanation": {"type": "string"}, "points": {"type": "number", "default": 1}}}}, "shuffleQuestions": {"type": "boolean", "default": False}, "shuffleOptions": {"type": "boolean", "default": False}, "showFeedback": {"type": "boolean", "default": True}}}},
    {"type_id": "multi-select", "display_name": "Multiple Select", "category": "assessment", "icon": "check-square", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["score"], "default_completion_type": "score", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["quiz", "multi-select", "assessment"], "sort_order": 41},
    {"type_id": "true-false", "display_name": "True / False", "category": "assessment", "icon": "toggle-left", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["score"], "default_completion_type": "score", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["quiz", "true-false", "assessment"], "sort_order": 42},
    {"type_id": "fill-blanks", "display_name": "Fill in the Blanks", "category": "assessment", "icon": "edit", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["score"], "default_completion_type": "score", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["quiz", "fill-blanks", "assessment"], "sort_order": 43},
    {"type_id": "matching", "display_name": "Matching", "category": "assessment", "icon": "link", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["score"], "default_completion_type": "score", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["quiz", "matching", "assessment"], "sort_order": 44},
    {"type_id": "scenario-question", "display_name": "Scenario-Based Question", "category": "assessment", "icon": "help-circle", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["score"], "default_completion_type": "score", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["scenario-step"]}, "tags": ["quiz", "scenario", "assessment"], "sort_order": 45},
    {"type_id": "knowledge-check", "display_name": "Knowledge Check", "category": "assessment", "icon": "clipboard", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["score"], "default_completion_type": "score", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["quiz", "knowledge-check", "assessment"], "sort_order": 46},
    {"type_id": "final-assessment", "display_name": "Final Assessment", "category": "assessment", "icon": "award", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["score"], "default_completion_type": "score", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["quiz", "final", "assessment"], "sort_order": 47, "schema": {"type": "object", "required": ["questions"], "properties": {"introText": {"type": "string"}, "passingScore": {"type": "integer", "minimum": 0, "maximum": 100, "default": 80}, "maxAttempts": {"type": "integer", "minimum": 1, "default": 1}, "shuffleQuestions": {"type": "boolean", "default": False}, "shuffleOptions": {"type": "boolean", "default": False}, "showCorrectAnswers": {"type": "boolean", "default": True}, "questions": {"type": "array", "minItems": 1, "items": {"type": "object", "required": ["id", "type", "question"], "properties": {"id": {"type": "string"}, "type": {"type": "string", "enum": ["mcq", "multiple-select", "true-false", "fill-in-blank"]}, "question": {"type": "string"}, "options": {"type": "array", "minItems": 2, "items": {"type": "object", "required": ["id", "text", "isCorrect"], "properties": {"id": {"type": "string"}, "text": {"type": "string"}, "isCorrect": {"type": "boolean"}}}}, "correctAnswer": {"type": "boolean"}, "correctAnswers": {"type": "array", "minItems": 1, "items": {"type": "string"}}, "explanation": {"type": "string"}, "points": {"type": "number", "default": 1}}}}}}},

    # ── Comparison & Analysis ────────────────
    {"type_id": "comparison-table", "display_name": "Comparison Table", "category": "comparison", "icon": "columns", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["comparison", "table"], "sort_order": 50},
    {"type_id": "pros-cons", "display_name": "Pros and Cons", "category": "comparison", "icon": "thumbs-up", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["pros", "cons", "comparison"], "sort_order": 51},
    {"type_id": "before-after", "display_name": "Before and After", "category": "comparison", "icon": "arrow-right", "scoring_enabled": False, "completion_capabilities": ["view", "interact"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["before", "after", "comparison"], "sort_order": 52},
    {"type_id": "matrix-grid", "display_name": "Matrix / Grid", "category": "comparison", "icon": "grid", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["matrix", "grid", "comparison"], "sort_order": 53},

    # ── Media-Rich ───────────────────────────
    {"type_id": "video-slide", "display_name": "Video-Based Slide", "category": "media-rich", "icon": "film", "scoring_enabled": False, "completion_capabilities": ["view", "audio"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["video", "media", "slide"], "sort_order": 60},
    {"type_id": "audio-slide", "display_name": "Audio-Based Slide", "category": "media-rich", "icon": "headphones", "scoring_enabled": False, "completion_capabilities": ["audio"], "default_completion_type": "audio", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["audio", "media", "slide"], "sort_order": 61},
    {"type_id": "animated-explainer", "display_name": "Animated Explainer", "category": "media-rich", "icon": "play", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["animation", "explainer", "media"], "sort_order": 62},
    {"type_id": "infographic", "display_name": "Infographic", "category": "media-rich", "icon": "bar-chart-2", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["infographic", "visual", "media"], "sort_order": 63},

    # ── Microlearning ────────────────────────
    {"type_id": "microlearning-cards", "display_name": "Microlearning Cards", "category": "microlearning", "icon": "credit-card", "scoring_enabled": False, "completion_capabilities": ["view", "interact"], "default_completion_type": "view", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["card"]}, "tags": ["microlearning", "cards", "bite-sized"], "sort_order": 70},
    {"type_id": "flashcards", "display_name": "Flashcards", "category": "microlearning", "icon": "copy", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["card"]}, "tags": ["flashcards", "study", "memory"], "sort_order": 71},
    {"type_id": "quick-tips", "display_name": "Quick Tips", "category": "microlearning", "icon": "zap", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["tips", "quick", "bite-sized"], "sort_order": 72},

    # ── Navigation & Structural ──────────────
    {"type_id": "course-menu", "display_name": "Course Menu", "category": "navigation", "icon": "menu", "scoring_enabled": False, "completion_capabilities": [], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["menu", "navigation", "structure"], "sort_order": 80},
    {"type_id": "learning-roadmap", "display_name": "Learning Roadmap", "category": "navigation", "icon": "map", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["roadmap", "navigation", "overview"], "sort_order": 81},
    {"type_id": "module-overview", "display_name": "Module Overview", "category": "navigation", "icon": "book", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["module", "overview", "navigation"], "sort_order": 82},
    {"type_id": "summary", "display_name": "Summary / Key Takeaways", "category": "navigation", "icon": "bookmark", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["summary", "takeaways", "recap"], "sort_order": 83},
    {"type_id": "resources-downloads", "display_name": "Resources & Downloads", "category": "navigation", "icon": "download", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["resources", "downloads", "files"], "sort_order": 84},

    # ── Gamification ─────────────────────────
    {"type_id": "quiz-game", "display_name": "Quiz Game", "category": "gamification", "icon": "trophy", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["score"], "default_completion_type": "score", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["game", "quiz", "gamification"], "sort_order": 90},
    {"type_id": "points-badges", "display_name": "Points and Badges", "category": "gamification", "icon": "award", "scoring_enabled": False, "completion_capabilities": [], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["points", "badges", "gamification"], "sort_order": 91},
    {"type_id": "progress-tracker", "display_name": "Progress Tracker", "category": "gamification", "icon": "trending-up", "scoring_enabled": False, "completion_capabilities": [], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["progress", "tracker", "gamification"], "sort_order": 92},
    {"type_id": "level-learning", "display_name": "Level-Based Learning", "category": "gamification", "icon": "layers", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["interact", "score"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["levels", "progression", "gamification"], "sort_order": 93},

    # ── Compliance & Corporate ───────────────
    {"type_id": "policy-acknowledgement", "display_name": "Policy Acknowledgement", "category": "compliance", "icon": "check-square", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["policy", "acknowledgement", "compliance"], "sort_order": 100},
    {"type_id": "dos-donts", "display_name": "Do's and Don'ts", "category": "compliance", "icon": "alert-circle", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["dos", "donts", "compliance"], "sort_order": 101},
    {"type_id": "code-of-conduct", "display_name": "Code of Conduct", "category": "compliance", "icon": "shield", "scoring_enabled": False, "completion_capabilities": ["view", "interact"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["code-of-conduct", "ethics", "compliance"], "sort_order": 102},
    {"type_id": "regulatory-scenario", "display_name": "Regulatory Scenario", "category": "compliance", "icon": "alert-triangle", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["interact", "score"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["scenario-step"]}, "tags": ["regulatory", "scenario", "compliance"], "sort_order": 103},
    {"type_id": "audit-checklist", "display_name": "Audit Checklist", "category": "compliance", "icon": "clipboard", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["audit", "checklist", "compliance"], "sort_order": 104},

    # ── Diagnostic & Adaptive ────────────────
    {"type_id": "pre-assessment", "display_name": "Pre-Assessment", "category": "diagnostic", "icon": "activity", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["score"], "default_completion_type": "score", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["pre-assessment", "diagnostic", "placement"], "sort_order": 110},
    {"type_id": "diagnostic-quiz", "display_name": "Diagnostic Quiz", "category": "diagnostic", "icon": "search", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["score"], "default_completion_type": "score", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["diagnostic", "quiz", "adaptive"], "sort_order": 111},
    {"type_id": "skill-gap-analysis", "display_name": "Skill Gap Analysis", "category": "diagnostic", "icon": "bar-chart", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["skill-gap", "analysis", "diagnostic"], "sort_order": 112},
    {"type_id": "adaptive-path", "display_name": "Adaptive Learning Path", "category": "diagnostic", "icon": "git-branch", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["adaptive", "learning-path", "personalized"], "sort_order": 113},
    {"type_id": "recommendation-card", "display_name": "Recommendation Card", "category": "diagnostic", "icon": "star", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["recommendation", "suggestion", "diagnostic"], "sort_order": 114},

    # ── Practice & Simulation ────────────────
    {"type_id": "guided-practice", "display_name": "Guided Practice", "category": "practice", "icon": "compass", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": True, "perInteraction": True, "interactionPoints": ["step"]}, "tags": ["guided", "practice", "hands-on"], "sort_order": 120},
    {"type_id": "try-it-simulation", "display_name": "Try-It Simulation", "category": "practice", "icon": "play", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["simulation", "try-it", "practice"], "sort_order": 121},
    {"type_id": "software-simulation", "display_name": "Software Simulation", "category": "practice", "icon": "monitor", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["software", "simulation", "practice"], "sort_order": 122},
    {"type_id": "sandbox-practice", "display_name": "Sandbox Practice", "category": "practice", "icon": "box", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["sandbox", "free-form", "practice"], "sort_order": 123},
    {"type_id": "error-identification", "display_name": "Error Identification", "category": "practice", "icon": "x-circle", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["interact", "score"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["error", "identification", "practice"], "sort_order": 124},

    # ── Feedback & Reflection ────────────────
    {"type_id": "reflective-question", "display_name": "Reflective Question", "category": "feedback", "icon": "message-circle", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["reflection", "question", "feedback"], "sort_order": 130},
    {"type_id": "learner-journal", "display_name": "Learner Journal", "category": "feedback", "icon": "book", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["journal", "writing", "reflection"], "sort_order": 131},
    {"type_id": "self-assessment", "display_name": "Self-Assessment", "category": "feedback", "icon": "user-check", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["self-assessment", "rating", "feedback"], "sort_order": 132},
    {"type_id": "confidence-rating", "display_name": "Confidence Rating", "category": "feedback", "icon": "thermometer", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["confidence", "rating", "feedback"], "sort_order": 133},
    {"type_id": "action-planning", "display_name": "Action Planning", "category": "feedback", "icon": "target", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["action", "planning", "goals"], "sort_order": 134},

    # ── Social & Collaborative ───────────────
    {"type_id": "discussion-prompt", "display_name": "Discussion Prompt", "category": "social", "icon": "message-square", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["discussion", "social", "collaborative"], "sort_order": 140},
    {"type_id": "peer-review", "display_name": "Peer Review", "category": "social", "icon": "users", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["peer", "review", "collaborative"], "sort_order": 141},
    {"type_id": "poll-vote", "display_name": "Poll / Vote", "category": "social", "icon": "bar-chart", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["poll", "vote", "survey"], "sort_order": 142},
    {"type_id": "team-challenge", "display_name": "Team Challenge", "category": "social", "icon": "flag", "scoring_enabled": True, "max_score": 100, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["team", "challenge", "collaborative"], "sort_order": 143},
    {"type_id": "scenario-debate", "display_name": "Scenario Debate", "category": "social", "icon": "message-circle", "scoring_enabled": False, "completion_capabilities": ["interact"], "default_completion_type": "interact", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["scenario", "debate", "discussion"], "sort_order": 144},

    # ── Accessibility & Support ──────────────
    {"type_id": "accessibility-tip", "display_name": "Accessibility Tip Card", "category": "accessibility", "icon": "eye", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["accessibility", "tip", "wcag"], "sort_order": 150},
    {"type_id": "keyboard-nav-guide", "display_name": "Keyboard Navigation Guide", "category": "accessibility", "icon": "command", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["keyboard", "navigation", "accessibility"], "sort_order": 151},
    {"type_id": "screen-reader-guide", "display_name": "Screen Reader Guide", "category": "accessibility", "icon": "volume-2", "scoring_enabled": False, "completion_capabilities": ["view", "audio"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["screen-reader", "guide", "accessibility"], "sort_order": 152},
    {"type_id": "language-selector", "display_name": "Language Selector", "category": "accessibility", "icon": "globe", "scoring_enabled": False, "completion_capabilities": [], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["language", "i18n", "accessibility"], "sort_order": 153},
    {"type_id": "transcript-page", "display_name": "Transcript / Caption Page", "category": "accessibility", "icon": "file-text", "scoring_enabled": False, "completion_capabilities": ["view"], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["transcript", "caption", "accessibility"], "sort_order": 154},

    # ── Analytics & Learning Insight ─────────
    {"type_id": "progress-summary", "display_name": "Learning Progress Summary", "category": "analytics", "icon": "pie-chart", "scoring_enabled": False, "completion_capabilities": [], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["progress", "summary", "analytics"], "sort_order": 160},
    {"type_id": "performance-dashboard", "display_name": "Performance Dashboard", "category": "analytics", "icon": "activity", "scoring_enabled": False, "completion_capabilities": [], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["performance", "dashboard", "analytics"], "sort_order": 161},
    {"type_id": "skill-mastery-report", "display_name": "Skill Mastery Report", "category": "analytics", "icon": "trending-up", "scoring_enabled": False, "completion_capabilities": [], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["skill", "mastery", "analytics"], "sort_order": 162},
    {"type_id": "completion-certificate", "display_name": "Completion Certificate", "category": "analytics", "icon": "award", "scoring_enabled": False, "completion_capabilities": [], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["certificate", "completion", "analytics"], "sort_order": 163},
    {"type_id": "manager-review", "display_name": "Manager Review Page", "category": "analytics", "icon": "briefcase", "scoring_enabled": False, "completion_capabilities": [], "default_completion_type": "view", "audio_support": {"perComponent": False, "perInteraction": False}, "tags": ["manager", "review", "analytics"], "sort_order": 164},
]


async def seed_component_types(session: AsyncSession) -> int:
    """Seed or update all 89 component types. Returns count."""
    repo = ComponentTypeRepository(session)
    count = 0
    for item in COMPONENT_TYPES:
        type_id = item.pop("type_id")
        await repo.upsert(type_id, **item)
        item["type_id"] = type_id  # Put it back for idempotency
        count += 1
    return count
