"""Course data builder for JavaScript injection."""
from typing import Dict, Any
import json
from .base import BaseBuilder


class CourseDataBuilder(BaseBuilder):
    """Builds course_data.js containing course structure."""

    async def build(self, context: Dict[str, Any]) -> str:
        """Build the course data JavaScript file."""
        course_data = {
            'courseId': context['course_id'],
            'title': context['title'],
            'templates': context['templates']
        }
        
        # Serialize with proper JSON encoding
        json_str = json.dumps(course_data, ensure_ascii=False, indent=2)
        
        return f'''// Course data generated by SCORM Export Service
const courseData = {json_str};

// Expose to global scope for player
if (typeof window !== 'undefined') {{
    window.courseData = courseData;
}}
'''
