"""add branching social analytics interactions

Revision ID: 759356cfebd6
Revises: 20250101_0002
Create Date: 2026-02-09 12:27:12.964418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '759356cfebd6'
down_revision: Union[str, Sequence[str], None] = '20250101_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_page_id', sa.String(length=64), nullable=True),
    sa.Column('source_component_id', sa.String(length=64), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('default_target_page_id', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_rules_branch_id'), 'branch_rules', ['branch_id'], unique=True)
    op.create_index(op.f('ix_branch_rules_course_id'), 'branch_rules', ['course_id'], unique=False)
    op.create_table('discussion_threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=True),
    sa.Column('author_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_threads_course_id'), 'discussion_threads', ['course_id'], unique=False)
    op.create_index(op.f('ix_discussion_threads_page_id'), 'discussion_threads', ['page_id'], unique=False)
    op.create_index(op.f('ix_discussion_threads_thread_id'), 'discussion_threads', ['thread_id'], unique=True)
    op.create_table('interaction_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('learner_id', sa.String(length=128), nullable=False),
    sa.Column('interaction_type', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_events_component_id'), 'interaction_events', ['component_id'], unique=False)
    op.create_index(op.f('ix_interaction_events_course_id'), 'interaction_events', ['course_id'], unique=False)
    op.create_index(op.f('ix_interaction_events_event_id'), 'interaction_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_interaction_events_interaction_type'), 'interaction_events', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_interaction_events_learner_id'), 'interaction_events', ['learner_id'], unique=False)
    op.create_index(op.f('ix_interaction_events_page_id'), 'interaction_events', ['page_id'], unique=False)
    op.create_table('peer_review_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=True),
    sa.Column('author_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_review_submissions_course_id'), 'peer_review_submissions', ['course_id'], unique=False)
    op.create_index(op.f('ix_peer_review_submissions_submission_id'), 'peer_review_submissions', ['submission_id'], unique=True)
    op.create_table('polls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('allow_multiple', sa.Boolean(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_course_id'), 'polls', ['course_id'], unique=False)
    op.create_index(op.f('ix_polls_poll_id'), 'polls', ['poll_id'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_course_id'), 'teams', ['course_id'], unique=False)
    op.create_index(op.f('ix_teams_team_id'), 'teams', ['team_id'], unique=True)
    op.create_table('branch_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('branch_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('learner_id', sa.String(length=128), nullable=False),
    sa.Column('matched_condition_index', sa.Integer(), nullable=False),
    sa.Column('target_page_id', sa.String(length=64), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch_rules.branch_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_events_branch_id'), 'branch_events', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_events_course_id'), 'branch_events', ['course_id'], unique=False)
    op.create_index(op.f('ix_branch_events_event_id'), 'branch_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_branch_events_learner_id'), 'branch_events', ['learner_id'], unique=False)
    op.create_table('discussion_replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reply_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('author_id', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parent_reply_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['discussion_threads.thread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_replies_reply_id'), 'discussion_replies', ['reply_id'], unique=True)
    op.create_index(op.f('ix_discussion_replies_thread_id'), 'discussion_replies', ['thread_id'], unique=False)
    op.create_table('peer_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=64), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('reviewer_id', sa.String(length=128), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('rubric_scores', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['peer_review_submissions.submission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_reviews_review_id'), 'peer_reviews', ['review_id'], unique=True)
    op.create_index(op.f('ix_peer_reviews_submission_id'), 'peer_reviews', ['submission_id'], unique=False)
    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vote_id', sa.String(length=64), nullable=False),
    sa.Column('poll_id', sa.String(length=64), nullable=False),
    sa.Column('voter_id', sa.String(length=128), nullable=False),
    sa.Column('selected_options', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.poll_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_votes_poll_id'), 'poll_votes', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_votes_vote_id'), 'poll_votes', ['vote_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poll_votes_vote_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_poll_id'), table_name='poll_votes')
    op.drop_table('poll_votes')
    op.drop_index(op.f('ix_peer_reviews_submission_id'), table_name='peer_reviews')
    op.drop_index(op.f('ix_peer_reviews_review_id'), table_name='peer_reviews')
    op.drop_table('peer_reviews')
    op.drop_index(op.f('ix_discussion_replies_thread_id'), table_name='discussion_replies')
    op.drop_index(op.f('ix_discussion_replies_reply_id'), table_name='discussion_replies')
    op.drop_table('discussion_replies')
    op.drop_index(op.f('ix_branch_events_learner_id'), table_name='branch_events')
    op.drop_index(op.f('ix_branch_events_event_id'), table_name='branch_events')
    op.drop_index(op.f('ix_branch_events_course_id'), table_name='branch_events')
    op.drop_index(op.f('ix_branch_events_branch_id'), table_name='branch_events')
    op.drop_table('branch_events')
    op.drop_index(op.f('ix_teams_team_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_course_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_polls_poll_id'), table_name='polls')
    op.drop_index(op.f('ix_polls_course_id'), table_name='polls')
    op.drop_table('polls')
    op.drop_index(op.f('ix_peer_review_submissions_submission_id'), table_name='peer_review_submissions')
    op.drop_index(op.f('ix_peer_review_submissions_course_id'), table_name='peer_review_submissions')
    op.drop_table('peer_review_submissions')
    op.drop_index(op.f('ix_interaction_events_page_id'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_learner_id'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_interaction_type'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_event_id'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_course_id'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_component_id'), table_name='interaction_events')
    op.drop_table('interaction_events')
    op.drop_index(op.f('ix_discussion_threads_thread_id'), table_name='discussion_threads')
    op.drop_index(op.f('ix_discussion_threads_page_id'), table_name='discussion_threads')
    op.drop_index(op.f('ix_discussion_threads_course_id'), table_name='discussion_threads')
    op.drop_table('discussion_threads')
    op.drop_index(op.f('ix_branch_rules_course_id'), table_name='branch_rules')
    op.drop_index(op.f('ix_branch_rules_branch_id'), table_name='branch_rules')
    op.drop_table('branch_rules')
    # ### end Alembic commands ###
