"""add_template_definitions_table

Revision ID: b0c884a961c3
Revises: 20251007_0002
Create Date: 2025-11-27 17:16:36.346186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c884a961c3'
down_revision: Union[str, Sequence[str], None] = '20251007_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_definition', sa.JSON(), nullable=False),
    sa.Column('render_template', sa.Text(), nullable=False),
    sa.Column('default_assets', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_id', 'version', name='uq_template_type_version')
    )
    op.create_index(op.f('ix_template_definitions_type_id'), 'template_definitions', ['type_id'], unique=False)
    # SQLite doesn't support ALTER COLUMN - skip those changes
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN - skip those changes
    op.drop_index(op.f('ix_template_definitions_type_id'), table_name='template_definitions')
    op.drop_table('template_definitions')
    # ### end Alembic commands ###
