// ============================================
// COURSE DATA - Generated by eLearning Platform
// SCORM Package: test
// Generated: 2026-05-10T18:16:18.257697
// ============================================

// Define courseData as a global variable
// This will be safely initialized by the player
var courseData = {
  "courseId": "course_1778417149553",
  "exportContractVersion": "2026-04-12.1",
  "title": "test",
  "author": "Course Author",
  "version": "1.0.0",
  "language": "en",
  "supportedTemplateTypes": [
    "accordion",
    "analytics-view",
    "branching-scenario",
    "breadcrumb",
    "calculator",
    "code-snippet",
    "content",
    "content-image",
    "content-media",
    "content-text",
    "content-video",
    "course-map",
    "course-menu",
    "data-visualization",
    "decision-tree",
    "drag-and-drop",
    "fill-in-blank",
    "flashcard",
    "form",
    "heat-map",
    "hotspot",
    "image-hotspots",
    "infographic",
    "interactive-tool",
    "key-takeaways",
    "learning-objectives",
    "learning-roadmap",
    "matching",
    "mcq",
    "metric",
    "module-overview",
    "multiple-select",
    "progress-tracker",
    "quiz",
    "quotation",
    "rich-text-editor",
    "role-play",
    "scenario",
    "sidebar-navigation",
    "stepper",
    "summary-takeaways",
    "tabs",
    "timeline",
    "transcript-caption",
    "true-false"
  ],
  "templates": [
    {
      "id": "d51af058-9aac-455d-8ff7-160e0e1be973",
      "type": "content-media",
      "order": 0,
      "title": "Text with Media",
      "data": {
        "content": "sdsdfsd",
        "subtitle": null,
        "videoUrl": null,
        "questions": null,
        "tabs": null,
        "panels": null,
        "body": "sdsdfsd",
        "mediaUrl": "https://amtrustfinancial.com/getmedia/b50eaa25-b5e7-4d07-9b85-1f3d7e36fd25/ANA_AmTrust_Remote_Worker_Best_Practices_Social_1200X628-min.jpg",
        "mediaType": "image",
        "mediaPosition": "right"
      },
      "pageId": "ba669340-981e-491f-9258-422356e991c2"
    }
  ],
  "totalSlides": 1,
  "createdAt": "2026-05-10T12:46:18.186044"
};

// Validation check
if (typeof courseData !== 'object' || !courseData.templates) {
    console.error('ERROR: courseData not properly loaded');
    console.error('courseData type:', typeof courseData);
    console.error('courseData value:', courseData);
    throw new Error('Course data initialization failed');
}

console.log('✓ Course data loaded successfully');
console.log('  Slides:', courseData.templates.length);
console.log('  Title:', courseData.title);
